import { Selector } from 'testcafe'
fixture `Teste de ícones`
    .page `https://marcelobritowd.github.io/im-hungry/`

    test('Itens com ícones incorretos ⚠', async t => {
        await t
        .maximizeWindow()
        .wait(1000*2)
        .hover("body > main > ul.products-list > product:nth-child(1) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(2) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(3) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(4) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(5) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(6) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(7) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(8) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(10) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(11) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(12) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(13) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(14) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(15) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(16) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(17) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(18) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(19) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(20) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(21) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(22) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(23) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(24) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.products-list > product:nth-child(25) > li > span.title-item.ng-binding")
        .wait(1000)
        .hover("body > main > ul.list-categories > li:nth-child(4) > a > span")
        .wait(1000*2)
    })